"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os

from setuptools import setup


def get_files(path):
    return [(d, [os.path.join(d, f) for f in files])
            for d, folders, files in os.walk(path)]

OPTIONS = {'includes': ["PyQt5", "yapsy", "colored", "tinydb", "prompt_toolkit", "pycopa"]}

setup(
    app=["./app.py"],
    data_files=get_files("./plugins") + get_files(""),
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
